 # stage 1
FROM python:3.9-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt --target=/app/deps
EXPOSE 5000

 # stage 2
FROM gcr.io/distroless/python3-debian12
WORKDIR /app
COPY --from=builder /app/deps /app/deps
COPY app.py .
COPY templates/ .templates/
EXPOSE 5000
ENV PYTHONPATH=/app/deps
CMD ["app.py"]
